# Generated by Django 4.1.3 on 2022-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
