# Generated by Django 4.1.3 on 2022-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search',
            field=models.CharField(default='Product', max_length=30),
            preserve_default=False,
        ),
    ]
